language: java
jdk:
  - openjdk11

os: 
  - linux
  
dist:
  - debian
  
addons:
    sonarcloud:
        organization: "jacopofabi"
        token: "ab2b7e3875651dea99866bb998c7b9441ce785ae"
        
script: 
    - mvn clean install
    - mvn sonar:sonar -Dsonar.projectKey=jacopofabi_JCS-ISW2 -Dsonar.organization=jacopofabi -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=ab2b7e3875651dea99866bb998c7b9441ce785ae -Dsonar.coverage.jacoco.xmlReportPaths=${project.buid.directory}/site/jacoco/jacoco.xml