language: java
jdk:
  - openjdk11

os: 
  - linux
  
dist:
  - debian
  
addons:
    sonarcloud:
        organization: "jacopofabi"
        token: "ab2b7e3875651dea99866bb998c7b9441ce785ae"
        
script: 
  # the following commands build the project, run the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Pcoverage -Dsonar.projectKey=jacopofabi_JCS-ISW2

    
  #- mvn clean verify sonar:sonar -Pcoverage
  #- sonar-scanner