language: java
jdk:
  - openjdk16

addons:
    sonarcloud:
        organization: "jacopofabi"
        token: "ab2b7e3875651dea99866bb998c7b9441ce785ae"
        
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=jacopofabi_JCS-ISW2
  - sonar-scanner